---
- hosts: localhost
  vars_files:
    - vars/packages_vars.yml
    - vars/openshift_vars.yml
#    - vars/add_nodes_multiple_interface_vars.yml
    - vars/add_nodes_vars.yml
  tasks:
    - name: Download rhcos-{{ openshift_minor_version }}-{{ architecture }}-installer.iso and rhcos-{{ openshift_minor_version }}-{{ architecture }}-metal.raw.gz
      get_url:
        url: "{{ item }}"
        dest: ./files/
      loop: "{{ openshift_install_url }}"
      ignore_errors: yes
      tags: an1
    - name: rename rhcos-{{ openshift_minor_version }}-{{ architecture }}-metal-bios.raw.gz to rhcos-{{ openshift_minor_version }}-{{ architecture }}-metal.raw.gz
      command: mv files/rhcos-{{ openshift_minor_version }}-{{ architecture }}-metal.x86_64.raw.gz files/rhcos-{{ openshift_minor_version }}-{{ architecture }}-metal.raw.gz
#      command: mv files/rhcos-{{ openshift_minor_version }}-{{ architecture }}-metal-bios.raw.gz files/rhcos-{{ openshift_minor_version }}-{{ architecture }}-metal.raw.gz
      ignore_errors: yes
      tags: an2
    - name: Create ignition file template file for all node
#      script: ./add_ocp_static_worker_ignition_recreated.sh
      script: ./add_ocp_static_worker_nodes.sh
      tags: an3
    - name: Create pxe-node file
      template:
        src: templates/pxe-node.j2
        dest: "~/openshift/{{ CLUSTERID }}/{{ item.node_name_short }}.pxe"
      loop: "{{ nodes }}"
      tags: an4
    - name: Create pxe-node file
      template:
        src: templates/pxe-boot-menu.j2
        dest: "~/openshift/{{ CLUSTERID }}/default"
      tags: an5
    - name: "Append default pxe boot menu with content of pxe-node file"
      shell: cat ~/openshift/{{ CLUSTERID }}/{{ item.node_name_short }}.pxe >> ~/openshift/{{ CLUSTERID }}/default
      loop: "{{ nodes }}"
      tags: an6
    - name: Copy default pxe boot menu to /var/lib/tftpboot/pxelinux.cfg/default
      copy:
        src: "~/openshift/{{ CLUSTERID }}/default"
        dest: /var/lib/tftpboot/pxelinux.cfg/
      tags: an7
    - name: Copy rhcos-{{ openshift_minor_version }}-{{ architecture }}-live-kernel-x86_64 to /var/www/html/
      copy:
        src: "files/rhcos-{{ openshift_minor_version }}-{{ architecture }}-live-kernel-x86_64"
        dest: /var/www/html/
      tags: an8
    - name: Copy rhcos-{{ openshift_minor_version }}-{{ architecture }}-live-initramfs.x86_64.img to /var/www/html/
      copy:
        src: "files/rhcos-{{ openshift_minor_version }}-{{ architecture }}-live-initramfs.x86_64.img"
        dest: /var/www/html/
      tags: an9
    - name: Copy rhcos-{{ openshift_minor_version }}-{{ architecture }}-live-rootfs.x86_64.img to /var/www/html/
      copy:
        src: "rhcos-{{ openshift_minor_version }}-{{ architecture }}-live-rootfs.x86_64.img"
        dest: /var/www/html/
      tags: an10
